### PR TITLE
account delete done

### PR DESCRIPTION
**Pull request by d-libards**

### CODE REVIEW

**Comment by Android-James** [comment]
bat nawala yung mg divs na may doctorAccount na ID? puro patient lang. may js effects kase yun kaya magkaiba


image

yung id patient pero yung result is doctor

**Comment by d-libards** [comment]
Ahh oki conopy paste ko lang kasi e

**Comment by Android-James** [comment]
gagi bat naclose. pano iopen ulit

**Comment by Android-James** [comment]
actually hayaan mo na. nakawhile loop pala sa back end di rin gagana yung js effects. mauulit lang yung id

**Review by Android-James — APPROVED** [review]

**Pull request merged**
